backbone:
  name: mobilenet2
  pretrained: true
regression_head:
  dense_struct:
    - 128
  activation: leaky_relu
  final_activation: sigmoid
keypoints_names:
  - left_eye_center
  - right_eye_center
  - left_eye_inner_corner
  - left_eye_outer_corner
  - right_eye_inner_corner
  - right_eye_outer_corner
  - left_eyebrow_inner_end
  - left_eyebrow_outer_end
  - right_eyebrow_inner_end
  - right_eyebrow_outer_end
  - nose_tip
  - mouth_left_corner
  - mouth_right_corner
  - mouth_center_top_lip
  - mouth_center_bottom_lip
target_resolution:
  height: 96
  width: 96